// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Settings: typeof import("./src/components/settings/index.vue")["default"];
    TAside: typeof import("tdesign-vue-next")["Aside"];
    TButton: typeof import("tdesign-vue-next")["Button"];
    TCard: typeof import("tdesign-vue-next")["Card"];
    TColorPickerPanel: typeof import("tdesign-vue-next")["ColorPickerPanel"];
    TConfigProvider: typeof import("tdesign-vue-next")["ConfigProvider"];
    TContent: typeof import("tdesign-vue-next")["Content"];
    TDrawer: typeof import("tdesign-vue-next")["Drawer"];
    TDropdown: typeof import("tdesign-vue-next")["Dropdown"];
    TDropdownItem: typeof import("tdesign-vue-next")["DropdownItem"];
    TDropdownMenu: typeof import("tdesign-vue-next")["DropdownMenu"];
    TFooter: typeof import("tdesign-vue-next")["Footer"];
    TForm: typeof import("tdesign-vue-next")["Form"];
    TFormItem: typeof import("tdesign-vue-next")["FormItem"];
    THeader: typeof import("tdesign-vue-next")["Header"];
    THeadMenu: typeof import("tdesign-vue-next")["HeadMenu"];
    TIcon: typeof import("tdesign-vue-next")["Icon"];
    TImage: typeof import("tdesign-vue-next")["Image"];
    TLayout: typeof import("tdesign-vue-next")["Layout"];
    TMenu: typeof import("tdesign-vue-next")["Menu"];
    TMenuItem: typeof import("tdesign-vue-next")["MenuItem"];
    TPopup: typeof import("tdesign-vue-next")["Popup"];
    TRadioButton: typeof import("tdesign-vue-next")["RadioButton"];
    TRadioGroup: typeof import("tdesign-vue-next")["RadioGroup"];
    TSubmenu: typeof import("tdesign-vue-next")["Submenu"];
    TSwitch: typeof import("tdesign-vue-next")["Switch"];
    TTooltip: typeof import("tdesign-vue-next")["Tooltip"];
  }
}
